//Hardcoded data until Api contact received
export const data = [
  {
    id: 1,
    prescriptionName: "Diabetes",
    doctorName: "Dr Shenelle Moses",
    datePrescribed: "08.10.2022",
    actions: "Test Action",
  },
  {
    id: 2,
    prescriptionName: "Heart",
    doctorName: "Dr Nafeel Niyas",
    datePrescribed: "09.10.2022",
    actions: "Test Action",
  },
  {
    id: 3,
    prescriptionName: "Lung",
    doctorName: "Dr Strange",
    datePrescribed: "10.10.2022",
    actions: "Test Action",
  },
  {
    id: 4,
    prescriptionName: "Liver",
    doctorName: "Dr Martino",
    datePrescribed: "11.10.2022",
    actions: "Test Action",
  },
  {
    id: 5,
    prescriptionName: "Anger",
    doctorName: "Dr Octopus",
    datePrescribed: "12.10.2022",
    actions: "Test Action",
  },
  {
    id: 6,
    prescriptionName: "Heart",
    doctorName: "Dr Nafeel Niyas",
    datePrescribed: "09.10.2022",
    actions: "Test Action",
  },
  {
    id: 7,
    prescriptionName: "Lung",
    doctorName: "Dr Strange",
    datePrescribed: "10.10.2022",
    actions: "Test Action",
  },
  {
    id: 8,
    prescriptionName: "Liver",
    doctorName: "Dr Martino",
    datePrescribed: "11.10.2022",
    actions: "Test Action",
  },
  {
    id: 9,
    prescriptionName: "Anger",
    doctorName: "Dr Octopus",
    datePrescribed: "12.10.2022",
    actions: "Test Action",
  },
  {
    id: 10,
    prescriptionName: "Diabetes",
    doctorName: "Dr Shenelle Moses",
    datePrescribed: "08.10.2022",
    actions: "Test Action",
  },
  {
    id: 11,
    prescriptionName: "Heart",
    doctorName: "Dr Nafeel Niyas",
    datePrescribed: "09.10.2022",
    actions: "Test Action",
  },
  {
    id: 12,
    prescriptionName: "Lung",
    doctorName: "Dr Strange",
    datePrescribed: "10.10.2022",
    actions: "Test Action",
  },
  {
    id: 13,
    prescriptionName: "Liver",
    doctorName: "Dr Martino",
    datePrescribed: "11.10.2022",
    actions: "Test Action",
  },
  {
    id: 14,
    prescriptionName: "Anger",
    doctorName: "Dr Octopus",
    datePrescribed: "12.10.2022",
    actions: "Test Action",
  },
  {
    id: 15,
    prescriptionName: "Heart",
    doctorName: "Dr Nafeel Niyas",
    datePrescribed: "09.10.2022",
    actions: "Test Action",
  },
  {
    id: 16,
    prescriptionName: "Lung",
    doctorName: "Dr Strange",
    datePrescribed: "10.10.2022",
    actions: "Test Action",
  },
  {
    id: 17,
    prescriptionName: "Liver",
    doctorName: "Dr Martino",
    datePrescribed: "11.10.2022",
    actions: "Test Action",
  },
  {
    id: 18,
    prescriptionName: "Anger",
    doctorName: "Dr Octopus",
    datePrescribed: "12.10.2022",
    actions: "Test Action",
  },
  {
    id: 19,
    prescriptionName: "Diabetes",
    doctorName: "Dr Shenelle Moses",
    datePrescribed: "08.10.2022",
    actions: "Test Action",
  },
  {
    id: 20,
    prescriptionName: "Heart",
    doctorName: "Dr Nafeel Niyas",
    datePrescribed: "09.10.2022",
    actions: "Test Action",
  },
  {
    id: 21,
    prescriptionName: "Lung",
    doctorName: "Dr Strange",
    datePrescribed: "10.10.2022",
    actions: "Test Action",
  },
  {
    id: 22,
    prescriptionName: "Liver",
    doctorName: "Dr Martino",
    datePrescribed: "11.10.2022",
    actions: "Test Action",
  },
  {
    id: 23,
    prescriptionName: "Anger",
    doctorName: "Dr Octopus",
    datePrescribed: "12.10.2022",
    actions: "Test Action",
  },
  {
    id: 24,
    prescriptionName: "Heart",
    doctorName: "Dr Nafeel Niyas",
    datePrescribed: "09.10.2022",
    actions: "Test Action",
  },
  {
    id: 25,
    prescriptionName: "Lung",
    doctorName: "Dr Strange",
    datePrescribed: "10.10.2022",
    actions: "Test Action",
  },
  {
    id: 26,
    prescriptionName: "Liver",
    doctorName: "Dr Martino",
    datePrescribed: "11.10.2022",
    actions: "Test Action",
  },
  {
    id: 27,
    prescriptionName: "Anger",
    doctorName: "Dr Octopus",
    datePrescribed: "12.10.2022",
    actions: "Test Action",
  },
];

export const columns = [
  {
    name: "Prescription Name",
    selector: (row: any) => row.prescriptionName,
    sortable: true,
  },
  {
    name: "Doctor Name",
    selector: (row: any) => row.doctorName,
    sortable: true,
  },
  {
    name: "Date Prescribe",
    selector: (row: any) => row.datePrescribed,
    sortable: true,
  },
  {
    name: "Actions",
    selector: (row: any) => row.actions,
  },
];
